### ISSUE TITLE
Windows virus detection on download

### ISSUE THREAD

**Issue by elemay** [RoseTheFlower/UltrawideIndex#10]
As I download The Quary ultrawide patch, Windows 11 prevents it to be written as it detect a virus in the archive (security version 1.367.1451.0).

Happens both with 1.0 and 1.1 versions.

**Comment by mrdigi** [comment]
This is rather normal for patches/mods that modify how a program runs and on the description page it makes mention of this:

"All trainers containing CE components may trigger some anti-virus software."

To allow it you can go into "Windows Security" -> "Virus & threat protection".  Under "Current Threats" click "Protection history".   There you will see the instances where it was blocked, and you can allow them by clicking on "Actions" -> "Allow".

**Comment by RoseTheFlower** [comment]
Closing as per mrdigi's valid explanation.
