### ISSUE TITLE
[Path of Exile 2 ] World map is broken

### ISSUE THREAD

**Issue by glassalle59** [RoseTheFlower/UltrawideIndex#100]
Hello !
First of all, thanks for this mod. It works great on POE2 except the world map.

The game itself work well with this mod. However the world map is broken and it is not possible to use it an travel to the differents locations.

Is it possible to fix that ?

Sincerely,

**Comment by Vraknel** [comment]
Map is fixed with the PoE2 specific version released a couple hours ago. https://github.com/RoseTheFlower/UltrawideIndex/releases/tag/pathofexile2

**Comment by glassalle59** [comment]
Wow sorry did not see that. Thanks a lot !
