### ISSUE TITLE
[PoE2] UI elements at the edge of the screen

### ISSUE THREAD

**Issue by Schmetterfliege** [RoseTheFlower/UltrawideIndex#104]
The fix for my Samsung 32:9 is awesome, but I don't know how to get the UI elements to be more centered.
The screenshot in the description (HDR screenshot by William) has everything but the quests centered to 16:9 I guess.
On my screen, everything is all the way at the edges, which makes it hard to monitor my health, for example.

Is there a setting to get the UI to show like shown in the screenshot?

mine:
![Bild_2024-12-09_153949077](https://github.com/user-attachments/assets/5aa62e73-ed70-4744-988b-cdbf2502181e)

**Comment by awdel** [comment]
In the game settings: Interface > General > Centred UI check box

**Comment by Schmetterfliege** [comment]
> In the game settings: Interface > General > Centred UI check box

omg, I checked the options up and down and somehow overlooked this...
Thank you very much!
