### ISSUE TITLE
[Neva] 5120x2160 resolution not working

### ISSUE THREAD

**Issue by ygonnik** [RoseTheFlower/UltrawideIndex#107]
After installing the patch, only 2560x1080 appeared on 5120x2160 screen.

**Comment by RoseTheFlower** [comment]
![image](https://github.com/user-attachments/assets/51026284-3c0e-4bbc-9705-5d3c8767c50f)

Works on my machine (TM).

**Comment by ygonnik** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/1e295616-7900-4aed-abd5-30131124865d)
I tried reinstalling, patching before the first launch with screen scaling at 100% (instead of 200%). Unsuccessfully. 😥

**Comment by RoseTheFlower** [comment]
You could try the generic solution of [using Borderless Gaming](https://www.wsgf.org/dr/rumbleverse/en) to add to the patcher. If that doesn't help, it could be something to do with your game version or the way you patch.
