### ISSUE TITLE
[POE2] Launch option required on Linux that is not in the README

### ISSUE THREAD

**Issue by TheOddball** [RoseTheFlower/UltrawideIndex#110]
`WINEDLLOVERRIDES="version=n,b" %command%`

This launch option is required in Steam to load the mod, and is not in the README

**Comment by RoseTheFlower** [comment]
It's covered by my [global Linux instructions](https://github.com/RoseTheFlower/UltrawideIndex/blob/main/instructions/linux.md), and from what I know, there are multiple ways to achieve the same thing, so I don't want to recommend just one. Moreover, including the instructions on each specific mod page would imply they have been tested with the solution, but I can't say that or properly provide support without having a Linux distro installed.
