### ISSUE TITLE
POE2 - Stash not working

### ISSUE THREAD

**Issue by Champosarus** [RoseTheFlower/UltrawideIndex#111]
Thanks for all the hard work, it looks amazing in Ultrawide!

Not sure if its just me or anyone else, but i'm unable to deposit items into my stash. Items i drop in go red, and the quick transfer with shortcut keys does not work either.

**Comment by RoseTheFlower** [comment]
I could not reproduce the issue. I had no problem moving an item to the town stash at 32:9 with the mod in place.

**Comment by Champosarus** [comment]
I figured out the issue. I have the game for both PS5 and PC. When you purchase tabs on PS5 they turn into remove only tabs on PC and vice versa.

Thanks again for the awesome work !
