### ISSUE TITLE
Path of Exile 2 super ultrawide and wider HAS A VIRUS

### ISSUE THREAD

**Issue by Paspasote** [RoseTheFlower/UltrawideIndex#112]
BE CAREFUL! DO NOT DOWNLOAD THIS. Eset antivirus claims it has a threat:  ML/Augur.C

**Comment by RoseTheFlower** [comment]
ML is machine learning, so it's not definitive. The false flagging of all kinds of files has been discussed at length now, so I'm closing. See #19 for a more detailed response and explanation.
