### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by falconmick** [RoseTheFlower/UltrawideIndex#15]
Kinda weird having this here on github and not including source code. Also when you download source on the release it’s just the readme files… am I missing something here?

**Comment by zhocef** [comment]
Agreed, especially considering this is gets flagged as a virus.

**Comment by falconmick** [comment]
I mean free software is free so I don’t want to come across as ungrateful, it’s just I really want to play the games and this stupid issue is stopping me, but I just can’t use this without the assurance that I’m not gonna brick my computer

**Comment by RoseTheFlower** [comment]
After I decided to switch away from PCGW, I looked for a platform that would allow me to not only host files but also track the download counts. A fellow creator recommended GitHub and convinced me that it's fine to use even if the source code is not to be provided.

The code of most of my solutions is quite accessible to anyone with basic knowledge of reverse engineering (sometimes to the detriment of the community, as there are a few blatant copies without any attribution or ability to improve based on user feedback). A few are literally open source or just bytes to find and replace but I see no net benefit in sharing the source of every single one.

The issue of false flagging is addressed in detail on [this page](https://www.reddit.com/r/widescreengamingforum/wiki/index/#wiki_.22there_is_a_virus_in_one_of_your_files.21.22). It's also worth adding that unless you review the code of and manually compile everything you use (which rules out the Windows OS, for example), even if the software is open-source, you still trust someone that the binary is actually from that code without anything extra. So if you do trust Microsoft, for example, nothing stops you from following the advice of the page I linked and submitting any of my files for them to review. I've done it to a couple but it's tedious to do each time I put out an update.

**Comment by falconmick** [comment]
Oh yeah 100% just because source is out there doesn’t mean you can trust exe, but it does mean I can check source and compile myself.

tbh it’s just not worth the time to learn decompilation for a single annoying issue in a game, lazy I know but I’ve not got heaps of time to spare in my life

**Comment by mirh** [comment]
There's not much point in allowing/having those "source code" links in every release then, isn't it?
(also, I thought you were winding down your mod activity in general not distancing from PCGW specifically?)

**Comment by RoseTheFlower** [comment]
Let me know if there's a way to not show those archives! As for PCGW, no, if anything, I believed that the need for me to depart from the platform would allow for more time to spend on modding, although it was not the reason.

**Comment by uvw** [comment]
@RoseTheFlower, it's not possible to exclude source code zips from releases without using GitHub API directly, **However**, you can exclude everything from the zips, making it clear that there is nothing useful inside. Just add `.gitattributes` in the root directory of your repository containing:

```
** export-ignore
```

This will exclude all files recursively from the source code zip archives.

**Comment by RoseTheFlower** [comment]
> you can exclude everything from the zips, making it clear that there is nothing useful inside

Thanks. I did this but the archive is still created and its size is not shown as 0 on the page, so it's only upon opening that it's clear that it's empty.

**Comment by dahlstrum** [comment]
I apologize for not having seen this old issue when I raised mine. I, as well, do not want to come across as grateful and I can understand each of the points made about why it's not the case. Even supplying "source code" files with the very sound reasoning you've mentioned here would be great. I just wasnt sure if there was some sort of automation process that you had for building/uploading that just didnt work. I can easily go through the efforts of decompilation given what's been said, I just tend to not lean on that as a first step. Thank you for the efforts you've done.

**Comment by ObsidianMinor** [comment]
The exes are Cheat Engine trainers. There's projects to unpack the exes like [dumbasPL/cetrainer-unpacker](https://github.com/dumbasPL/cetrainer-unpacker) which produce the CE binary, LUA defines, and CETRAINER file (which is just XML). It would be great if the trainer and defines were in the repo, but I guess this is ok.
