### ISSUE TITLE
Virus on the ultrawide fix

### ISSUE THREAD

**Issue by pokerapar88** [RoseTheFlower/UltrawideIndex#19]
![image](https://user-images.githubusercontent.com/11278553/182464628-b0e71194-90d5-48b4-84c1-262e10676881.png)
![image](https://user-images.githubusercontent.com/11278553/182464684-5cb2cdd7-229b-4283-8d73-fa0c8114bccd.png)

**Comment by RoseTheFlower** [comment]
Explained in detail [here](https://www.reddit.com/r/widescreengamingforum/wiki/index/) and briefly on the description page of the solution. Also [read about heuristics](https://en.wikipedia.org/wiki/Heuristic_(computer_science)#Antivirus_software) ("Heur" in your screenshot) and feel free to [submit the file to Norton](https://support.norton.com/sp/en/us/home/current/solutions/kb20090602171902EN) for a manual (and hopefully proper) review.
