### ISSUE TITLE
Virus Alert on Tunic.ultrawide.v1.1.MS.Store.Game.Pass.zip

### ISSUE THREAD

**Issue by hvogelpohl** [RoseTheFlower/UltrawideIndex#2]
Cannot Download this file on Chrome Windows 10

**Comment by RoseTheFlower** [comment]
See if there is a way to ignore the warning and force Chrome to download. If not, look in the settings for anything "malware"-related and disable the malware filter for a few minutes just to download. The reason it happens is detailed [here](https://www.reddit.com/r/widescreengamingforum/wiki/index#wiki_.22there_is_a_virus_in_one_of_your_files.21.22).

**Comment by hvogelpohl** [comment]
worked. Thank you.
