### ISSUE TITLE
Linux version of fix for Disney Dreamlight Valley via Proton

### ISSUE THREAD

**Issue by Zaclovespenguins** [RoseTheFlower/UltrawideIndex#26]
Hello! I'm running on linux and came across this fix for ultrawide support. Unfortunately there isn't a way to run the fix via proton as it's all contained in an exe. Are there any manual instructions? Or potentially a way to compile it for linux as well? 

Thanks!

**Comment by RoseTheFlower** [comment]
Hi, are you on Discord? I could send you an alternative version for Steam to test before making it public, just to ensure there are no serious bugs.

**Comment by Zaclovespenguins** [comment]
Yes, I am! Do you have a server I can join or can I dm you my info?

**Comment by RoseTheFlower** [comment]
Sure, you could join [the WSGF server](https://discord.gg/4wbu65NQGn) and then DM me.

**Comment by K1whi** [comment]
Hello! Starting to play this day, running also linux to play :) Did you manage to do it via Proton ?

**Comment by RoseTheFlower** [comment]
@LeTabouret told me that [Bottles](https://usebottles.com/) allowed them to successfully target the game process with my fix.

**Comment by RoseTheFlower** [comment]
The game has native support for ultrawide now. Closing.
