### ISSUE TITLE
Dreamlight Valley 16:10 fix?

### ISSUE THREAD

**Issue by Dantasstic** [RoseTheFlower/UltrawideIndex#27]
Any way to get this to work with 16:10 resolutions as well?

**Comment by RoseTheFlower** [comment]
It already does, though via the default Unity scaling of hor- compared to 16:9. Looking for a way to target the FOV specifically for narrower resolutions is beyond the scope of what I typically do here.

**Comment by Dantasstic** [comment]
Gotcha. Yeah, it works, but the UI gets all smashed together when opening menus and inventory. Hopefully the game gets updated to allow for other resolutions at some point.

**Comment by RoseTheFlower** [comment]
I don't see it at 1920x1200. Can you provide a screenshot?

**Comment by Dantasstic** [comment]
![Disney Dreamlight Valley Screenshot 2022 09 23 - 23 55 18 92](https://user-images.githubusercontent.com/48727187/192082469-d03cc2cf-8954-4a5d-9ac1-25c873519d50.png)
![Disney Dreamlight Valley Screenshot 2022 09 23 - 23 55 55 06](https://user-images.githubusercontent.com/48727187/192082477-d5b8f35d-ff00-4bce-bc7b-f5590028f56a.png)

**Comment by Dantasstic** [comment]
This is at 2560x1600

**Comment by RoseTheFlower** [comment]
If you apply the fix once to force the game to use your resolution, then restart the game and do not apply the fix, then the UI should be good for 16:10 without the overlapping.

**Comment by Dantasstic** [comment]
Yes, the storage issue is gone! :) Goofy's stall still gets cut off a tiny bit, but is very playable now. Appreciate it!
