### ISSUE TITLE
Far Cry 5 won't launch with FOV fix installed

### ISSUE THREAD

**Issue by sthdevilish** [RoseTheFlower/UltrawideIndex#32]
Hey, thank you for awesome job you're doing for ultrawide users!

I'm having trouble with Far Cry 5 and FOV fix https://github.com/RoseTheFlower/UltrawideIndex/releases/tag/farcry5 installed. If I try to launch the game (doesn't matter if it's from Ubisoft app or directly executable for the game), it will be stuck at splash screen with cursor indicating that something is loading. If I go to task manager, FarCry5.exe is there but state is constantly flashing between nothing and "paused". If I delete either of the both files (FarCry5FOV.asi or version.dll), it launches without a problem.

Steps already made on my side:
1) restarted Ubisoft app
2) verified game files (all is ok)
3) tried running FC5 as admin

Only deleting fix works, however there is a FOV slider in the game and its maxed at 104, so I guess I'll be fine for 21:9 ratio.

**Comment by RoseTheFlower** [comment]
Thanks. The game must have been updated, as the code is slightly altered. I updated the solution to make it work again. In the future, I should just code in a check to allow it to proceed if it can't find any of the code it seeks.

**Comment by sthdevilish** [comment]
Thank you, version 1.1 seems to be working fine, in the option slider shows higher FOV values than 104. Didn't test yet in-game.
