### ISSUE TITLE
(Trek to Yomi) Steam Version does not fill screen correctly with 48:9

### ISSUE THREAD

**Issue by baggyg** [RoseTheFlower/UltrawideIndex#33]
![a71c70ae-b411-4d09-aef4-0b11aa046fee](https://user-images.githubusercontent.com/4569081/206455707-4b251934-778f-43a0-83a7-40c468a21c9a.jpg)

Downloaded archive and put everything in Engine/Binaries/Win64. In game set the settings to 5760x1080. Tried both full screen and borderless window. No change. 

The scene loading icon is correctly on the very far left, but all scenes and menus show this.

**Comment by RoseTheFlower** [comment]
Hi, I don't think you followed the instructions correctly. The Engine folder is what it says. The game exe folder is Ronin.

**Comment by baggyg** [comment]
Indeed, I am an idiot.
