### ISSUE TITLE
Death Stranding DC (Epic) download: Program:Win32/Uwamson.A!ml - Microsoft Defender removal 

### ISSUE THREAD

**Issue by Rechain** [RoseTheFlower/UltrawideIndex#34]
Every time I download the Director's Cut (Epic) version I get this from Microsoft Defender and it gets removed (Program:Win32/Uwamson.A!ml) not even sure I wanna allow it. Even though false positives have been an issue before, I just don't trust much when something like this is detected. Also, the non-DC version I have used before I upgraded the game there was nothing like this 🤔 anyone else??

**Comment by RoseTheFlower** [comment]
See my responses in #12 or #10.
