### ISSUE TITLE
Ultrawide fix makes the new update of the quarry crash 

### ISSUE THREAD

**Issue by batiti93** [RoseTheFlower/UltrawideIndex#35]

**Comment by RoseTheFlower** [comment]
Added a bypass as a hotfix.

**Comment by batiti93** [comment]
wow, so fast!! how did you find the solution so quickly????

**Comment by RoseTheFlower** [comment]
I try to keep every game installed and maintain the solutions through updates. I looked into this one right after the update as well. The hotfix is not ideal in that it's a two-part solution, so I've been looking into reworking the main fix but you all forced my hand! :D
