### ISSUE TITLE
Remove black bars in sexy brutale for old screen (4:3 format)

### ISSUE THREAD

**Issue by mrdeathjr28** [RoseTheFlower/UltrawideIndex#37]
hi

is posssible remove black bars in sexy brutale for old screen (4:3 format aka 1024x768)

thanks

**Comment by RoseTheFlower** [comment]
Hi, I had access to the game via the EA Play subscription but it was removed from it. The request is also outside the scope of this repo. I'll close it and may or may not revisit it in the future if I end up having the game.
