### ISSUE TITLE
Application Disappears after launching - DS: Director's Cut Widescreen Fix

### ISSUE THREAD

**Issue by gibifernand** [RoseTheFlower/UltrawideIndex#4]
Should I be worried? I launched DS Director's Cut on Steam, then launched the extracted app as seen on the instructions. Icon and app just vanishes afterwards.

**Comment by gibifernand** [comment]
Never mind, found it was because of the antivirus software. Quick question: Is there a way to have changes stay persistent when closing/opening the game? Or do i really need to adjust the resolution to fix the black bars via the app each time i open the game?

thanks.

**Comment by RoseTheFlower** [comment]
Yes, but you could try using one of the patchers from [here](https://community.pcgamingwiki.com/files/file/1940-death-stranding-ultrawide-fix-fov-changer/), then just use the trainer for the FMVs and the FOV changer if you need it.
