### ISSUE TITLE
Disney Dreamlight Valley: Stutter and game freeze after April 5th patch

### ISSUE THREAD

**Issue by Guff08** [RoseTheFlower/UltrawideIndex#40]
Disney Dreamlight Valley: Needs to be updated for new game client patch for April 5th. Currently causes the game to stutter and freeze.

**Comment by RoseTheFlower** [comment]
There were some changes to the code and I updated the fix just now to cover those. Give the new version a try and let me know of the outcome!

**Comment by Guff08** [comment]
New version seems to work great. Thanks!
