### ISSUE TITLE
Stuck at 4608x720 on 32:9 monitor

### ISSUE THREAD

**Issue by beatdowniidx** [RoseTheFlower/UltrawideIndex#41]
after enabling game get stuck at 4608x720

**Comment by RoseTheFlower** [comment]
Which game?

**Comment by beatdowniidx** [comment]
Death stranding directors cut

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RoseTheFlower** [comment]
It's a known issue, previously discussed in #3. I linked to a workaround in that thread.
