### ISSUE TITLE
Batman Arkham Knight - No mission markers and Riddler Trial falling out of bounds

### ISSUE THREAD

**Issue by SolidusSpy** [RoseTheFlower/UltrawideIndex#44]
Hi there, I have been using the cutscene fov fix on 3440x1440 and noticed a persistent issue where the top compass does not show a waypoint for any selected missions which makes navigation difficult for later missions. I have also found that I cannot progress in the first Riddler Trial after entering into it with the batmobile because the level fails to load as the elevator descends and I fall out of bounds once the character reaches the bottom.

Only other mod I have installed is the Arkham Knight community patch but after uninstalling that I can confirm these problems only occur with the ultrawide fix installed even after verifying integrity of game files in Steam. I appreciate any and all help with this!

**Comment by RoseTheFlower** [comment]
Do you have a save file I could use to easily reproduce this? A screenshot would and the exact steps to reproduce would help as well.

Speaking generally, the FOV fix is expected to be specific to that and I'm not modifying any other code, whereas the pillarboxing removal is shader/texture-based, so any issues like falling through would be very weird and inconsistent with my fix.

**Comment by SolidusSpy** [comment]
Thank you, yes here it is:

**Comment by SolidusSpy** [comment]
[BAK1Save0x0.zip](https://github.com/RoseTheFlower/UltrawideIndex/files/11950370/BAK1Save0x0.zip)
![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/138553505/045f2736-4cb6-4b6e-8c59-834850e89c7c)

**Comment by SolidusSpy** [comment]
The save file I have attached spawns right outside of the challenge so you can drive into it to see the effect. Pressing V and selecting a mission shows a waypoint to its location on the top compass under regular gameplay but is unaffected with the fix applied.

**Comment by RoseTheFlower** [comment]
Thanks a lot for bringing this up. I reproduced both using your save file. The reason it happened under the bridge is that the FOV increase was being applied there, effectively pushing the camera outside the boundaries of the box under the water.

Try the updated version and let me know how it goes.

**Comment by SolidusSpy** [comment]
I can confirm the update fixes the Riddler Trial camera bug, I can progress through the loading and complete it without any problems - thank you very much! I believe the fov change has also added back in some missing effects during first person cutscenes such as in the opening diner sequence

Unfortunately I still can't see the mission markers and I have noticed a regression with the map screen in this new release: the map icons appear very dark and blurry but appear normal when closing in and out of the map quickly. I have tested with the 1.0 fix and the map screen works as intended there.

![map](https://github.com/RoseTheFlower/UltrawideIndex/assets/138553505/661d6d76-1725-4846-b591-7a7290ab0cb6)

**Comment by RoseTheFlower** [comment]
Could you give me an example of the quest mark not showing on the compass? From your save file, I'm not seeing it even without the fix in place. The way I tested for it was by starting a new game and checking for the green mark on the compass as soon as I got to play as Batman.

**Comment by SolidusSpy** [comment]
Apologies for not clarifying beforehand, but it looks as though the main misssion does not leave a mark at that point in the save file. Selecting another mission like the Riddler's Revenge should show a mark leading to the elevator after tabbing in and out to get rid of the level up prompt.

![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/138553505/f2f9c865-98ff-4a12-bcb8-d0c0b0e12866)

A better example would be like how you tested when you first play as Batman because on my end the compass is showing blank with the fix applied and pressing V this early does nothing so there is no way to enable or disable markers. 

![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/138553505/ce0cb013-e655-4f5c-9d4c-f512be8a421b)

**Comment by RoseTheFlower** [comment]
Try the new version. It took a whole day to find the right code and target it that way rather than as a shader.

**Comment by SolidusSpy** [comment]
Awesome work, I've restarted my game save up to where I last left off with the Riddler Trial and have not encountered any of the previous bugs (mission markers, map screen and Riddler Trial works perfectly). Thanks again for making the ultrawide experience for this game even better!
