### ISSUE TITLE
dll override for Uncharted widescreen fix in Proton

### ISSUE THREAD

**Issue by grahfmusic** [RoseTheFlower/UltrawideIndex#45]
Just wondering what dll override would I need to use to get the Uncharted widescreen fix to work correctly with Proton?

**Comment by RoseTheFlower** [comment]
version to native and builtin, after the file name.

**Comment by grahfmusic** [comment]
so version.dll

**Comment by grahfmusic** [comment]
Thank you that worked.  So any dll in any of your patches I have to override. Thank you so much for the ultimately quick response :)
