### ISSUE TITLE
Halls of torment text alignment when opening chests

### ISSUE THREAD

**Issue by robertino129** [RoseTheFlower/UltrawideIndex#46]
Hello. If it isn't too much of a hassle, could somebody that knows this programming language please take a look to see whether the text alignment for 32:9 when picking up items is an easy fix? The text box is huge when in inventory screen, covering most of the screen 

![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/5997278/36101227-9c19-4555-a694-6ceb6451a81f)

And, unfortunately, also huge when picking up a chest. However the text box is shifted way to the right on mouseover which usually means you don't even see a word of it.
![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/5997278/2e297929-b488-4fa6-9ce9-326de83d3515)

**Comment by Tadiian** [comment]
Yeah same issue on 21:0. If this is fixable it would be nice.

**Comment by RoseTheFlower** [comment]
Could you try to see if the new v1.1 addresses this?

**Comment by TacoTime1** [comment]
I get this in 21:9 with v1.1 though not to the extent of OP. But, there is text still getting cut when opening chests.

**Comment by RoseTheFlower** [comment]
The game has native UW support now. Enable it via the Widescreen pillarbox slider.

![image](https://github.com/user-attachments/assets/04217ecc-1ba3-45f9-8882-d8935bf064ae)
