### ISSUE TITLE
Dreamlight Valley strange inventory behavior

### ISSUE THREAD

**Issue by CptKaluh** [RoseTheFlower/UltrawideIndex#47]
Hey, 

after some time the inventory in dreamlight valley is a little strange. When clicking with right mousebutton in on an inventory slot , another is triggered. When launching the game and applying the godsent widescreen fix, everything is good and the game is running smooth and correctly. this problem occurs after a while. Any chance this could be fixed ? i even dont know how and why this happens. 

Greetings

**Comment by RoseTheFlower** [comment]
Could you explain what you mean by another one being triggered? Are you absolutely certain this doesn't occur without the fix?

**Comment by CptKaluh** [comment]
Hey yeah. i try to explain. imagine there is a grid with items for every slot. for example, if you trigger slot 16  (which is food you eat in this case) you trigger another slot too.  This only happens when applying the fix (and i love this fix , it's just kinda frustrating because i double activate items when just clicking one slot) 

Of course im not a developer but for me it seems like if i "click a certain pixel , which is part of the inventory grid, i activate a different pixel too" 

i will try to make a video if possible 

greets and thanks for the quick respond

**Comment by RoseTheFlower** [comment]
Interesting. I play the game weekly when there is a new star path, but I haven't had the issue occur at 21:9.
There is no code that is activated after a delay from the initial modifications, so the delay doesn't make sense to me at all.
What is your resolution?

**Comment by CptKaluh** [comment]
my windows resolution is 3440 x 1440 (native) and ingame resolution with windowed(borderless mode) is 2550x1440. Maybe it has something to do with that ? 

i will add some pictures added, because there are some other things that might help to fix the problem or getting close to what the problem really come from. maybe i have to add the .bat or something ?

**Comment by CptKaluh** [comment]
like promised here two additional things i recognized when testing the fix. 

first picture is a dearranged menu , this might be normal due to no native 21:9 support from gameloft itself ? you can tell better ^^

second is using the camera tool ingame and taking a picture , then changing the camera modus to full screen by pressing T . the upper and lower border then vanish into off screen while the right and left border fitting as intended. 

![border off screen when taking a picture and change format of picturemode(ingame)](https://github.com/RoseTheFlower/UltrawideIndex/assets/140023600/5c6d5da8-6c42-40d7-95c0-42ae2ff0a379)
![weird menu scaling and pc setting](https://github.com/RoseTheFlower/UltrawideIndex/assets/140023600/9c51e339-dd9b-447f-8f5a-25465b88096e)

hopefully this worked with uploading. im new to github and pls dont laugh at my legendary paint skills :D

**Comment by RoseTheFlower** [comment]
Yeah, the stretching of the fullscreen photos is a known issue, just as when viewing artwork.

The non-centered placement of the menu elements is also to be expected, since we're rescaling the UI for a wider resolution.

I could probably address some of these issues with a more tailored approach to each scene, but the fix wouldn't be as reliable, so I've been postponing it, especially given that the issues are either not game-breaking or merely cosmetic, as with the menu.

**Comment by CptKaluh** [comment]
hehe no worries, im totally fine with this fix. you did great work. I hope we can solve the inventory thing too. i try to make a short video when it occurs again and upload it then. i still have no idea why this occurs. 

you play on the same resolution as me ?

**Comment by RoseTheFlower** [comment]
I'm at 2560x1080 and I specifically used from slot 16 today but any of the nearby slots were unaffected. It's the one in the center in this screenshot.
![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/4759227/c8e997ea-2366-4fa6-a308-cad9f6d201ef)

If you get it on video, I'll try to reproduce again but this time at 3440x1440.

**Comment by CptKaluh** [comment]
The slot was just an example, it happens to almost every slot, sometimes i press slot 14 and slot 6 is triggered too ^^ i try to reproduce it myself, until now it hasnt happen , but im kinda sure it will today. i upload video then.

**Comment by CptKaluh** [comment]
Yaix, i recreated it and i have an idea when this probably happens. 

https://github.com/RoseTheFlower/UltrawideIndex/assets/140023600/6f08c26f-3bcb-47f7-8b9e-fef898b58a1c

Before this happens everything was fine. then i did the quest with simba and had to put rafikis stick into its place to solve the cloud-riddle and after that it started happen. When i think back on last time it happens, i did the olaf quest and had to put something from inventory in its socket (gems and prisma and so on). Maybe this particular problem happens when i have to put something from the back into it's socket (via right click).

**Comment by CptKaluh** [comment]
And it's only a problem with right click. leftclick -> eat  works fine still.

**Comment by RoseTheFlower** [comment]
Thanks. Quests aside, can you think of another condition that could cause this?

**Comment by CptKaluh** [comment]
i tried several ways to reproduce the false inventory behavior but none worked out like the quest did. I even cant imagine how to fix this but hope's on you :) im watching this in particular and if another ingame action forces this problem to come up again , i definitely give alarm :D 

Restart of the game and applying the fix one again solves the inventory bug again but this is just a shorthanded fix then i dont wanne rely on too often hehe

**Comment by CptKaluh** [comment]
Ahh recreated again :D This time after taking something out of a selfmade chest 

https://github.com/RoseTheFlower/UltrawideIndex/assets/140023600/d001e100-6314-44fb-a6d5-3347b0aa96c8

It seems it has something in common with taking things or putting things with right click

**Comment by CptKaluh** [comment]
It's getting funnier.... and maybe this isnt a problem with the widescreen fix. Maybe it's a problem with the game itself and i have to tell gameloft. Cant tell if im the only one that has this problem. But in this clip... watch the paprica on the left side, while im clicking the storage item. really funny :) 


https://github.com/RoseTheFlower/UltrawideIndex/assets/140023600/35ff985a-ea9f-4fad-9b97-3dd9483b0cb7

**Comment by RoseTheFlower** [comment]
Yeah, I'm completely clueless as to why it may be happening. In theory, a rescale could be somewhat shifting something, though it's not how it tends to work in Unity, but the distance being so long is extremely weird. Have you ever played the game without the fix for hours?

**Comment by CptKaluh** [comment]
yeah i test really many things. i played a lot on 27 inch monitor with 16:9 2560x1440 and there the problem does not occur. it must have something in common with right clicking because it triggers something. i dont know. on 27" monitor i can put food into storage with right click and not eating the food at the same moment. With the fix applied and on the 3440x1440 resolution, when i put food into storage with right click i eat it at the same moment AND  putting it into storage (with one less amount of course)

**Comment by CptKaluh** [comment]
but tbh i dont get it either... im absolutely clueless too what triggers the bug. Im not quite sure if the fix trigger this problem or the game which does not support 21:9 in 2023 is the problem itself :D yesterday it took a long time for the problem to occur. today i forced it withing minutes :D But as an it-architect (which i am ) i really dont find any "base" when this thingy happens

**Comment by CptKaluh** [comment]
Here are some examples for things i tested on 27" with different resolutions: 

27" inch 2560x1440
https://github.com/RoseTheFlower/UltrawideIndex/assets/140023600/069a99f5-d78c-4643-a9ea-28731ac74105

27" 3440x1440 without fix
https://github.com/RoseTheFlower/UltrawideIndex/assets/140023600/eae078bd-05bc-43b9-8123-96527dfab892

27" 3440x1440 with fix 
https://github.com/RoseTheFlower/UltrawideIndex/assets/140023600/096b56d5-c659-4c8b-952d-ee4ca49399de

27" 3440x1440 forcing the bug (watch the stacksize of berrys when rightclicking them into storage) 

https://github.com/RoseTheFlower/UltrawideIndex/assets/140023600/939f8ab0-fa81-4afc-b3e7-13a256173631

**Comment by CptKaluh** [comment]
Hey you,

a short notice for this problem: this isnt a particular problem with the widescreen fix. It's a problem with the game itself. I opened a problem-case where it was confirmed and will be fixed soon in a later  update. So this Case can be closed here. For me i found a workaround (by playing with controller instead of mouse and keyboard). The only thing left is the dearranged menu when playing with the fix. Maybe you are able to even solve this problem soon ^^ 

Cheers

**Comment by RoseTheFlower** [comment]
I still haven't been able to reproduce, but it's good to know. Thanks!
