### ISSUE TITLE
Armored Core VI: Fires of Rubicon

### ISSUE THREAD

**Issue by BanditTech** [RoseTheFlower/UltrawideIndex#53]
would love to request a patch for this game! 

If there is anything I could provide to make it a reality, let me know.

**Comment by RoseTheFlower** [comment]
Hi, it's not a game I own, but I hear it already supports ultrawide [and much wider](https://www.youtube.com/watch?v=aG4wUhTtZhA).

For the cutscenes, according to mana2000, you can disable Easy Anti-Cheat and change 26 B4 17 40 to [your aspect ratio](https://www.wsgf.org/article/common-hex-values).

**Comment by BanditTech** [comment]
Thank you for the information, much appreciated.

**Comment by RoseTheFlower** [comment]
No worries. I'll close, as this doesn't relate to my existing fixes.
