### ISSUE TITLE
Weapon Laser Scope Misaligned (Starfield)

### ISSUE THREAD

**Issue by soulcr4ft** [RoseTheFlower/UltrawideIndex#55]
Hey, I just found out about your mod, thanks for helping the community, to give some context I was using the INI modifications to remove the pillarboxes for 32:9 and fix the map markers (fWideAspectLimit=3.55556) / bPhotoModeLetterBoxed=0), to increase the FOV (fFPWorldFOV=100.0000 / fTPWorldFOV=100.0000), to limit the UI safezone (fSafeZoneXWide=960), but didn't found any INI command to help with the weapon model being too close, to help with that I found a CheatEngine corretion to have different FOV value just for the weapon, so the FP and TP was set at 100 in the INI and the weapon at 140 with the CE method. (Starfield 21:9 Viewmodel/Weapon FOV Fix on Reddit, don't know if I can post links here). 

Your solution seems to give almost the same result as the INI + CE, the only differences/bugs I found so far are with the laser scope pointer weapons, where the laser itself seems to be stuck on the original place the weapon was when I play the game without the CE correction and the items images in the menus are squished, here are some screenshots, hope that they can help, thanks again for you work on this fix.

INI Fix Only:
![12 - INI Fix](https://github.com/RoseTheFlower/UltrawideIndex/assets/144563851/4df17b27-f5e6-45cd-b992-33dd201d7cc5)

INI Fix + CheatEngine Fix
![13 - INI Fix + CheatEngine Weapon Fix](https://github.com/RoseTheFlower/UltrawideIndex/assets/144563851/094a1a3e-bd6a-459c-b821-8b774604aa1e)

Rose Ultrawide (with both fWideAspectLimit and bPhotoModeLetterBoxed removed from the INI)
![14 - Rose Fix](https://github.com/RoseTheFlower/UltrawideIndex/assets/144563851/b53b8793-3a2b-4c60-9b51-4a19f9af52d9)

**Comment by RoseTheFlower** [comment]
Are you using the latest version of the fix, which is 1.1 at the time of this writing?

**Comment by soulcr4ft** [comment]
Oh, sorry, I should have checked before, can you delete this thread then? I was using the 1.0 version, just tried the 1.1 and the laser is fixed, thank you, only the squished items remains.
