### ISSUE TITLE
Chained Echoes 3840x1600

### ISSUE THREAD

**Issue by TerraDK** [RoseTheFlower/UltrawideIndex#57]
![Chained_Echoes_yF0vZ93Dkd](https://github.com/RoseTheFlower/UltrawideIndex/assets/46207023/086b11af-8201-4844-88ef-0b80463ca042)

Hello Rose,
Love your work. Thank you.

Unfortunately playing on 3840x1600, there are thick black bars on top and bottom. Is there something I can do to fix this?

**Comment by RoseTheFlower** [comment]
Thanks for the report. I found the culprit and removed those constraints. Try the latest version.

**Comment by TerraDK** [comment]
![Chained_Echoes_Rttotvoxo7](https://github.com/RoseTheFlower/UltrawideIndex/assets/46207023/995ae1c1-c40f-41bb-98e8-e2eb3dbca4e1)

Your v1.2.0 fix works beautifully. Thank you very much.
