### ISSUE TITLE
Ultrawide fix for Robocop possible?

### ISSUE THREAD

**Issue by Hoshi82** [RoseTheFlower/UltrawideIndex#59]
The usual tweaks like in the ini sadly don't work and as usual if not correctly implemented in Unreal Engine the game is cropped on top and bottom when setting to an aspect ratio of 21:9 or wider.

**Comment by RoseTheFlower** [comment]
Hi, if it's like the demo, the impression of the FOV being reduced is false. Try maxing out the FOV at 21:9, then switching to 16:9 and maxing out the FOV again and you'll see that. The weapon view is indeed reduced. @Lyall had a working fix for it for the demo and he shared some of the findings with me but I don't want to take the credit. Let's wait a bit to see if Lyall makes those findings into a working fix.

**Comment by Hoshi82** [comment]
Ok have to test with the max FOV slider but yeah, the reduced weapon view is a bit annoying in 21:9. Hope he can make a usable fix for that :) Thanks for the answer.

**Comment by RoseTheFlower** [comment]
Sadly, Lyall doesn't own the game, but after three days of non-stop work on a fix, at least I can say that most of it is my findings and all issues should be addressed. [Download here](https://github.com/RoseTheFlower/UltrawideIndex/releases/tag/robocoprc).

**Comment by Hoshi82** [comment]
Thank you!
