### ISSUE TITLE
[TUNIC] Needs updating after 22/04 patch (1.1.2.0)

### ISSUE THREAD

**Issue by Gliptal** [RoseTheFlower/UltrawideIndex#6]
The widescreen fixer doesn't work anymore on the GamePass version after the 1.1.2.0 update.

**Comment by RoseTheFlower** [comment]
Still works on my end, though you obviously have to re-patch the updated file. Step 2 is no longer necessary, so even the Steam / GOG patcher would work for Game Pass now.

**Comment by Gliptal** [comment]
The fact that you'd have to repatch the exe after an update completely escaped my mind for some reason.

Can confirm it still works, thanks!
