### ISSUE TITLE
[Robocop: Rogue City] Black Bars during cutscenes at 3840 x 1600 Resolution

### ISSUE THREAD

**Issue by AbbieDoobie** [RoseTheFlower/UltrawideIndex#60]
I am still getting black bars at 3840 x 1600 during cutscenes. Everything else appears to work (e.g. weapon view model isn't cut-off).

![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/8533148/f615e436-c0b5-4133-8ed4-4bb075fd8204)

**Comment by RoseTheFlower** [comment]
The letterboxing of some cutscenes is [not](https://youtu.be/K33itslmXvs?feature=shared&t=334) specific to ultrawide. As long as the horizontal view is expanded compared to 16:9, that should be fine. If I found a way to remove those bars, the horizontal FOV would decrease compared to now, as I prefer to maintain the devs' original vertical view to stick to their vision.

**Comment by AbbieDoobie** [comment]
Gotcha I see. My apologies, I misunderstood from the description what was to be expected. Closing this out, thank you!

**Comment by RoseTheFlower** [comment]
The description did say that the black bars are removed from _dialogue_, but just now I modified it to clarify that it refers to the vertical black bars.
