### ISSUE TITLE
The Last Faith UW 

### ISSUE THREAD

**Issue by CrimsonStarx** [RoseTheFlower/UltrawideIndex#61]
I just want to start off by saying thank you so much for the fix! I have ran into a couple issues so far. The 1st issue is that rooms that don't have a lot of left and right traversal are rendered really weirdly. I don't know if that is something that is even fixable or not on a modders end. The other issue I am running into is that the game just closes when travelling through doorways. It has closed on me about 5 times in 45 minutes of playing.

**Comment by RoseTheFlower** [comment]
Hi, do you have a screenshot of the parts that you think are rendered incorrectly? Regarding the issue of crashes, I haven't experienced that when going from area to area, so I'm not sure how to reproduce that.

**Comment by CrimsonStarx** [comment]
I'll get you a screenshot just give me a minute :)

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by CrimsonStarx** [comment]
________________________________

**Comment by CrimsonStarx** [comment]
I get the black on the edges of the screen because there's not actually any graphics there to load correct?

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by RoseTheFlower** [comment]
There are definitely some locations where the game has nothing to draw past the door or the wall. It might be one of the reasons the game does not natively support ultrawide.

**Comment by CrimsonStarx** [comment]
Okay that's kind of what I assumed was the issue. I will remove my issue of Github. Once again thank you for adding a fix to this. If I can figure out the crashing thing or replicate it I will be sure to let you know!

________________________________

**Comment by RoseTheFlower** [comment]
Sure, I'm open to investigating it if you can pinpoint it and I get a save file allowing me to reproduce it. I entered the first doorway in the game more than 10 times now and there was nothing abnormal. Previously I tested by going through multiple areas, too.
