### ISSUE TITLE
Late Shift 21:9 Not working

### ISSUE THREAD

**Issue by rolaindigo** [RoseTheFlower/UltrawideIndex#64]
Hi, i was trying to do my first play through "Late Shift" at 3440x1440, but your previous fix does not work anymore, any chance for an updated fix? thanks

There is no managed folder to put the dll in, ive tried to create the managed folder and put it there and even put it in few other places but there was no luck.

**Comment by RoseTheFlower** [comment]
Yeah, the game has been updated and switched to IL2CPP, making it harder to read its code. Still, I remade the fix and now made it dynamic to support not only 21:9 but also anything wider. Give it a try.

**Comment by rolaindigo** [comment]
> Yeah, the game has been updated and switched to IL2CPP, making it harder to read its code. Still, I remade the fix and now made it dynamic to support not only 21:9 but also anything wider. Give it a try.

THANK YOU, just started a new game and it works!
