### ISSUE TITLE
The Last Faith 3840x1600

### ISSUE THREAD

**Issue by TerraDK** [RoseTheFlower/UltrawideIndex#65]
Hello Rose;

I'm on a 38 UW resolution at 3840x1600. I've installed 1.0 patch and then the 1.2 patch. First launch was slow as you described but game still runs with black bars on left/right.

I've tried searching for my issue and installed [this package](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/) but same issue.

Game Version: 1.1.2 (Steam)
CPU:  i7-13900K
GPU: Gigabyte 4090
OS: Windows 11 version 22H2

**Comment by RoseTheFlower** [comment]
Try [this](https://cdn.discordapp.com/attachments/1174776451325775952/1188211979106668664/The_Last_Faith_ultrawide_v1.2.1_test_patch_requires_v1.0.zip) and let me know of the outcome. There should be no black bars but I'm not sure that the scaling would be right at that specific resolution.

**Comment by TerraDK** [comment]
Thank you for such a quick response. 

So it seems mostly fixed. Few screenshots for you.

1) Intro: That "Press Any Button" is supposed to be in middle, but not gameplay relevant.
![The_Last_Faith_QH0yjZR13K](https://github.com/RoseTheFlower/UltrawideIndex/assets/46207023/291539fa-f4bf-4790-b03d-633370846266)

2) Game: It seems fine and UI elements are fine as far as I can tell.
![The_Last_Faith_HTnbFKLWka](https://github.com/RoseTheFlower/UltrawideIndex/assets/46207023/c3bac2cf-6919-4534-b7c0-45bfd2abce07)

3) Inventory: Seems left side of the inventory is pushed all the way left. Works fine, however.
![The_Last_Faith_itOPR1wVhT](https://github.com/RoseTheFlower/UltrawideIndex/assets/46207023/d9454cdb-d0e8-44ff-b401-9f3aed67665c)

4) Character: Once again, works fine, but seem stretched out. Does not affect gameplay.
![The_Last_Faith_P59KiNQYtZ](https://github.com/RoseTheFlower/UltrawideIndex/assets/46207023/ae03b5a4-bc47-4d94-a54f-5f01b58c4af9)

So as of now, it works great and is playable. But I just linked those in case you wanted to adjust for future folks.

Happy Holidays & Merry Christmas also.

**Comment by RoseTheFlower** [comment]
Nice! I uploaded the new version to the main page as well.

As for the shifted UI elements, I made note of those issues when testing, but each would require a separate override, potentially making the fix less reliable. Sometimes I do this for overlapping elements but here I saw it as tolerable.

Happy holidays to you as well!

**Comment by TerraDK** [comment]
Sounds good. I just started the game so I might be missing but if I find any more issues, I'll reopen the ticket. 

Thank you for your quick work as always.
