### ISSUE TITLE
Halls of Torment Ultrawide mod may need update

### ISSUE THREAD

**Issue by Jmann1118** [RoseTheFlower/UltrawideIndex#66]
Game displays a large box blocking half of the screen when using ultrawide mod. Few other folks stating same issue on steam forums. This occurs once in gameplay, not in menus or town.

**Comment by Reynbow** [comment]
Can confirm. Mod works fine in menus and in the character select location, but once loaded into the game itself, it's quite broken.

**Comment by RoseTheFlower** [comment]
Thanks for reporting the issue. I checked the fix after most updates, but didn't think to leave the camp. I worked on the fix and sorting some build issues over the past days, but the newly uploaded v1.1 should solve the problem.

**Comment by Reynbow** [comment]
Thank you so much for the incredibly fast update!
There is... another issue, though I don't know if it's something you will be able to resolve, or have the time to look in to (totally fair enough).
When killing a boss (a few minutes in to a run), you get an item drop and it's difficult to read the descriptions as they can roll off screen. I've attached an image as an example.

![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/19285509/a8d698d3-b928-4656-9a17-c0c14c7ba386)

**Comment by RoseTheFlower** [comment]
Thanks. Let's close this if the OP issue is fixed.

The issue of tooltips is discussed in https://github.com/RoseTheFlower/UltrawideIndex/issues/46. I think my update changed the behavior of some of the tooltips, but clearly it didn't fix everything. I'm not sure how to go about addressing the problem but I'll keep it at the back of my mind.
