### ISSUE TITLE
The last faith - Camera not working on corner of Drowned Crypt

### ISSUE THREAD

**Issue by jamithbermudez** [RoseTheFlower/UltrawideIndex#68]
The camera is not moving on this corner of Drowned Crypt, using the patch 1.2.1
Game version 1.1.2

![The Last Faith 06_01_2024 01_59_52](https://github.com/RoseTheFlower/UltrawideIndex/assets/22222124/1f4311eb-9b37-46ad-9cf4-9d962d77bafa)

![The Last Faith 06_01_2024 01_59_58](https://github.com/RoseTheFlower/UltrawideIndex/assets/22222124/6dc61323-9013-46d2-b3f4-9706cbe64fb9)

![The Last Faith 10_01_2024 22_29_49](https://github.com/RoseTheFlower/UltrawideIndex/assets/22222124/fbc7482c-a58a-4cc9-81e3-c846643baa5b)

Proof
https://clips.twitch.tv/IgnorantLaconicChowderDancingBaby-qVZnr0lJZWpWcOH1

**Comment by RoseTheFlower** [comment]
Looks like the same issue as previously reported by a 32:9 user. It seems that no matter how much I try to make the level bounds adapt to ultrawide and wider, something breaks. Removing them comes at the cost of exposing unwanted areas and changing the camera framing from the original, but try this and let me know of your overall experience.
[The Last Faith ultrawide v1.3 test patch (requires v1.0).zip](https://github.com/RoseTheFlower/UltrawideIndex/files/13900453/The.Last.Faith.ultrawide.v1.3.test.patch.requires.v1.0.zip)

**Comment by jamithbermudez** [comment]
Sorry for the delay. I tested the patch and it works now, but I have to say that the previous implementation looked better.

https://youtu.be/0ImeaEfBSMI

**Comment by RoseTheFlower** [comment]
Thanks for the thorough test at that location and documenting it on video.

Yeah, those constraints are there for a reason but I see no way to modify all the boundaries created by the dev. The old versions will stay up in case people want to face the softlock and restart just to pass it.

**Comment by jamithbermudez** [comment]
I finished the game at 90% and only in that place where the camera malfunctioned, thanks a lot for the patch.
