### ISSUE TITLE
Detroit: Become Human is missing?

### ISSUE THREAD

**Issue by GrabbenD** [RoseTheFlower/UltrawideIndex#69]
Came across this lovely mod by Rose
https://community.pcgamingwiki.com/files/file/1721-detroit-become-human-ultrawide-multimonitor-mod/

Shouldn't it be in this repository?

**Comment by RoseTheFlower** [comment]
At this time, I'm not directly linking to the older fixes hosted elsewhere, but they can be found at [this link](https://github.com/RoseTheFlower/UltrawideIndex#more).
