### ISSUE TITLE
[Update] Tunic has been updated

### ISSUE THREAD

**Issue by nedex** [RoseTheFlower/UltrawideIndex#7]
Hello,
The ultrawide hack was working until now, but apparently today a new update has been pushed on the MS Store, being unable to patch the second file (`globalgamemanagers`) writing 0 bytes.
Could you please make a new release?

Thank you.

**Comment by RoseTheFlower** [comment]
No need. The new game update makes it obsolete, so you can either omit the step or use the GOG / Steam patcher. I'd remove the MS Store patcher but it would also remove the number of downloads associated with it.

**Comment by nedex** [comment]
I'm sorry I didn't find a changelog but apparently yes, the ultrawide is now natively supported.
Thank you anyways for the quick reply and the awesome work!

**Comment by RoseTheFlower** [comment]
It's supported only to the extent of being able to select your resolution, but the black bars still need to be patched out, so to speak. Thanks!
