### ISSUE TITLE
D4

### ISSUE THREAD

**Issue by Goddard** [RoseTheFlower/UltrawideIndex#70]
Diablo 4 beta worked with nvidia surround but now they seem to have removed it.  Would be cool if it worked.

**Comment by RoseTheFlower** [comment]
Hi, I've never released a fix for Diablo 4 and I don't own the game. I experimented a little during the last free weekend and found signs of protection, but it didn't seem to be too far-reaching at first glance. I might have another look when I own the game. Closing for now.
