### ISSUE TITLE
Death Stranding 1.004 (17/01/2024) - tool no longer works

### ISSUE THREAD

**Issue by littlebloke** [RoseTheFlower/UltrawideIndex#72]
As title, tool does not appear to work at all with the new version.

**Comment by RoseTheFlower** [comment]
Each of the toggles still works on my end on Steam. Just tested. What exactly is the problem you are experiencing?

**Comment by littlebloke** [comment]
Odd, maybe its me!

On steam also. Just came back to the game for a replay. 

When running the game, then tool, going into settings and hitting F5 i'm not getting my rez / loss of back bars when changing any settings. My desired rez (and monitor) is 3640x1600, Win11 23H2.

**Comment by RoseTheFlower** [comment]
Ah, see #3.

**Comment by littlebloke** [comment]
Understood... odd this, as i'm sure I had no issues before. But appreciate you taking the time to get back to me. :) Be safe, Be well.
