### ISSUE TITLE
Harold Halibut crashes almost all loading screen

### ISSUE THREAD

**Issue by Smatjoy** [RoseTheFlower/UltrawideIndex#75]
It lets me enter the game but when i change the room by going in a pipe or even sleep to change the day the game crashes.

**Comment by RoseTheFlower** [comment]
What's the quickest way to reach those from starting a new game?

**Comment by Smatjoy** [comment]
I added your fix in a save which was 4/5 hours after the beginning of the game. I continued to use that and I saw that the crashes only occur randomly every 3/4 loading screens.

**Comment by RoseTheFlower** [comment]
I'll close this in favor of #73. I haven't got to playing through the game, so 4-5 hours in would be impossible for me to reproduce.
