### ISSUE TITLE
[Request] Phantom Fury

### ISSUE THREAD

**Issue by Hoshi82** [RoseTheFlower/UltrawideIndex#76]
Sadly it's another UE4 game where the devs didn't implement the ultrawide aspect ratios propperly. Engin.ini tweaks like AspectRatioAxisConstraint=AspectRatio_MaintainYFOV don't work and the wider we go the closer the weapons/hand of the playercharacter gets zoomed in, besides the world zoomed in as usual.

It would be super nice if you could look into this and maybe an ultrawide fix is possible. :)

**Comment by RoseTheFlower** [comment]
The weapon meshes are always the hardest to fix, with no universal way to do it from game to game, as their implementations differ. I don't own the game at the moment but if I get access to it, I'll try to take a look.

**Comment by Hoshi82** [comment]
Thanks :)
