### ISSUE TITLE
Celeste 4:3 and 16:10 support

### ISSUE THREAD

**Issue by hmcneill46** [RoseTheFlower/UltrawideIndex#78]
Hey I was wondering if it would be possible to patch Celeste to run at 4:3 or 16:10, It would be great since [Portmaster](https://portmaster.games/) supports Celeste, and many devices that run Portmaster are 4:3. and the 16:10 would be great for the steam deck and macbooks,
Thanks for all the hard work!

**Comment by RoseTheFlower** [comment]
I'm not sure how the UI elements would behave when the view is made narrower. Either way, it would take as much if not more work as the ultrawide patches, with many different kinds of values changed in the game code. I specialize in ultrawide mods, but if it's not too hard to expand on that, also cover the narrow resolutions. Not a priority, but I'll keep it at the back of my mind.

**Comment by hmcneill46** [comment]
Cheers for the quick reply, and thanks again for the work!
