### ISSUE TITLE
Great job!!!

### ISSUE THREAD

**Issue by AkumaNervoso** [RoseTheFlower/UltrawideIndex#79]
Great job, Rose. Could you make ultrawide mod for Warhammer 40k Space Marine 2?

Thanks.

**Comment by RoseTheFlower** [comment]
Hi, I don't own the game. It's been reported that my WWZ patcher works to remove the black bars but results in the FOV being vert-. [This guide](https://framedsc.com/GameGuides/spacemarine2.htm) allows to adjust the FOV.

**Comment by AkumaNervoso** [comment]
what's WWZ patcher?

**Comment by RoseTheFlower** [comment]
https://community.pcgamingwiki.com/files/file/1295-world-war-z-ultrawide-multimonitor-fix-mostly-obsolete/
