### ISSUE TITLE
Tunic not working

### ISSUE THREAD

**Issue by Mic601** [RoseTheFlower/UltrawideIndex#8]
Is it just me or it's not working since the new patch? Or the instructions are really unclear.

**Comment by RoseTheFlower** [comment]
Both patchers still fix the game. Which parts are unclear?

**Comment by Mic601** [comment]
The regedit part is unclear. I can't access it in the patcher and it's not explained in the new instructions. It only mentions it in the old instructions.

**Comment by RoseTheFlower** [comment]
Those are for older versions of the game. The steps are not necessary anymore.

**Comment by Mic601** [comment]
So where to i find the globalgamemanagers file now? Can't find it in the game's files. And thank you for your quick response

**Comment by RoseTheFlower** [comment]
If you follow the new instructions and use the "GOG / Steam / more" patcher (even on Game Pass), it won't even have that step. For the Game Pass patcher, if you want to use it, just skip the second step. That change is part of the game now, so there's nothing to patch.

**Comment by Mic601** [comment]
AH ok! I was using the steam only patcher! Thank you!
