### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by antonovkz** [RoseTheFlower/UltrawideIndex#80]
https://www.virustotal.com/gui/file/8209d7237906f7acaeca7dce6a26f608b6425f2632a2838755178809f4cea08e?nocache=1

33/73

AliCloud
HackTool:Win/CheatEngine.A#
Antiy-AVL
HackTool[Hoax]/Win32.CheatEngine.a
Bkav Pro
W32.AIDetectMalware
CrowdStrike Falcon
Win/grayware_confidence_90% (D)
Cylance
Unsafe
Cynet
Malicious (score: 100)
DeepInstinct
MALICIOUS
Elastic
Malicious (high Confidence)
ESET-NOD32
A Variant Of Win32/HackTool.CheatEngine.AF Potentially Unsafe
Fortinet
Riskware/CheatEngine
GData
Win32.Riskware.Hacktool.D
Google
Detected
Ikarus
PUA.HackTool.Cheatengine
K7AntiVirus
Unwanted-Program ( 004b8a131 )
K7GW
Unwanted-Program ( 004b8a131 )
Lionic
Trojan.Win64.Cobalt.tpMn
Malwarebytes
Generic.Malware.AI.DDS
MaxSecure
Trojan.Malware.300983.susgen
McAfee Scanner
Real Protect-LS!D74A2521867B
Rising
Hacktool.CheatEngine!8.362 (CLOUD)
Sangfor Engine Zero
Hacktool.Win32.Cheatengine.V5xt
SentinelOne (Static ML)
Static AI - Suspicious PE
Skyhigh (SWG)
BehavesLike.Win32.Generic.tc
Sophos
Generic Reputation PUA (PUA)
Symantec
ML.Attribute.HighConfidence
TEHTRIS
Generic.Malware
Trapmine
Malicious.high.ml.score
Trellix (ENS)
PUP-IIH
Trellix (HX)
Generic.mg.d74a2521867bb368
TrendMicro-HouseCall
TROJ_GEN.R014H06B123
Varist
W32/ABRisk.WOEG-5678
Webroot
W32.Hacktool.Gen
Zillya
Tool.CheatEngine.Win32.17721

**Comment by RoseTheFlower** [comment]
Most of those are correct in that Cheat Engine is a "hacktool", "potentially unwanted program (PUP)", and "riskware". See [this](https://www.reddit.com/r/widescreengamingforum/wiki/index/#wiki_.22there_is_a_virus_in_one_of_your_files.21.22) for the rest and feel free to compile Cheat Engine from the source code today, build a trainer, then check that on VirusTotal.
