### ISSUE TITLE
Silent Hill widescreen reflections are stretched

### ISSUE THREAD

**Issue by tauruslondono** [RoseTheFlower/UltrawideIndex#84]
When using the widescreen patch (3440x1440 21:9), reflections are stretched horizontally. This is apparent in the opening cutscene, and the cutscene where Angela has the knife.

**Comment by Amon-akira** [comment]
even the intro is a bit stretched  :(

**Comment by RoseTheFlower** [comment]
> even the intro is a bit stretched :(

Could you clarify? The only thing I remember being stretched in the intro is the mirror reflection. I believe there are only three scenes featuring mirrors in the game (though I haven't played through yet). No solution found yet.

**Comment by Amon-akira** [comment]
i have done 2screen 16:9 and 21:9, the 21:9 is zoomed to fit in ultra wide format
![16 9](https://github.com/user-attachments/assets/4e5d2046-07f6-47ae-8600-6029528cb0ec)
![21 9](https://github.com/user-attachments/assets/55427b02-a0d9-4f87-9c6c-930fb6820fdd)

**Comment by RoseTheFlower** [comment]
That's not the case on my end. What's your desktop resolution when you're launching the game? The issue is separate from the thread subject, by the way, and I will mark it as off-topic soon.

![image](https://github.com/user-attachments/assets/2297bdfb-1fa1-4368-91d8-4b2776ec3ce6)

**Comment by Amon-akira** [comment]
3840x1620

**Comment by RoseTheFlower** [comment]
> 3840x1620

Then it shouldn't be an issue, assuming that it's the true **desktop** resolution that is active.

**Comment by Amon-akira** [comment]
> > 3840x1620
> 
> Then it shouldn't be an issue, assuming that it's the true **desktop** resolution that is active.

ok ok was a custom 1620p on 2160p display, but if i select it on desktop game is ok now

thx
