### ISSUE TITLE
Mod apparently causes massive cutscne stuttering with new game patch

### ISSUE THREAD

**Issue by DitherMan420** [RoseTheFlower/UltrawideIndex#87]
Hello, unfortunately I think this mod needs an update with the new patch. I haven't had a chance to test it myself but I am seeing multiple reports of massive stuttering with the mod due to today's patch. Supposedly, removing the mod fixes it. Any chance you can take a look? Might just need a quick update. Thanks!

**Comment by RoseTheFlower** [comment]
Which of the 100 mods hosted here?

**Comment by DitherMan420** [comment]
> Which of the 100 mods hosted here?

Oh I'm very sorry. I mistakenly posted this here. This is in regards to the Silent Hill 30fps cutscene fix mod.

**Comment by RoseTheFlower** [comment]
I didn't notice that with the patch at all. Any sure way to reproduce? Best to move the discussion to #83.

**Comment by DitherMan420** [comment]
> I didn't notice that with the patch at all. Any sure way to reproduce? Best to move the discussion to #83.

Well that's good. Could be those people had other things causing it. Maybe a mod conflict too.
