### ISSUE TITLE
Silent hill 2 Remake, UltraWide 21/9 resolution on 16/9 screen ?

### ISSUE THREAD

**Issue by Obaemon7** [RoseTheFlower/UltrawideIndex#89]
Hi there,
I'm used to play game in ultrawide on my 16/9 TV, with a custom resolution (nvidia control panel) of 3840 * 1600.
However at the moment in Silent Hill, the game revert to 16/9 if i enable the HDR, i don't know why. I try fullscreen and window no border, but it always revert to 16/9 in HDR, even if i have a 21/9 resolution in windows.

Any idea ?

**Comment by RoseTheFlower** [comment]
That doesn't seem to be related to my mod, as it has no functionality that enforces ultrawide resolutions. Its purpose is removing the black bars from the cutscenes.

**Comment by Obaemon7** [comment]
Oh yeah sorry, i know it's not related to your mod, i was hoping maybe you had an idea about how to fix this issue.

**Comment by RoseTheFlower** [comment]
After setting the game to fullscreen rather than borderless, you could try setting your resolution in GameUserSettings.ini via ResolutionSizeX= and ResolutionSizeY= (with the game closed, obviously). That's the only suggestion I have.

**Comment by Obaemon7** [comment]
I'll try that, thanks

**Comment by Obaemon7** [comment]
Yeah it doesn't work, if i put the game in 3840*1600 (21/9) it stays in that resolution, but the image is stretched to 16/9. It doesn't keep the 21/9 ratio. I think it something to do with hdr, because when i launch game, the screen flickers because the TV recognize the game as an HDR content, and when i launch silent hill, i can see the screen menu with the nice 21/9 screen ratio for a second, before the TV flickers ans stretch the image to 16/9. Anyway, i know it's not really your job, i will try to find a solution, i remember using some patches for this in certain games.

**Comment by RoseTheFlower** [comment]
Fair. I'll close so it doesn't look like an issue with my mods.
