### ISSUE TITLE
Graphic glitches and crashes (The Quarry)

### ISSUE THREAD

**Issue by GodzillasTodespranke** [RoseTheFlower/UltrawideIndex#9]
I get graphic glitches (TV noise, one colored screen) and the game crashes usually when these glitches occur.

Edit: Missed the new v1.1! I will report back if the game runs without issues.

**Comment by RoseTheFlower** [comment]
1.1 should address the issues but the 80s filter and the path chosen screen are still improperly displayed. I looked into it and experimented with narrowing down the relevant function but couldn't address the issue. I'm hoping for a revelation in my mind or a mod that removes those effects and serves as a workaround.

**Comment by RoseTheFlower** [comment]
I just released version 1.2, which should fix the issues with the 80s filter and the Path Chosen screen. Please test it out and close the issue if it's good on your end. I was told that 1.1 addressed the crashes.

**Comment by GodzillasTodespranke** [comment]
Thanks, will do. I'm going to start a 2nd playthrough today. I don't have the 80s filter, though.

**Comment by GodzillasTodespranke** [comment]
Path chosen works now. Thank you! :)
