### ISSUE TITLE
(Silent hill 2 remake) dlss to fsr3 mod incompatible with the fix

### ISSUE THREAD

**Issue by DiamondQarp** [RoseTheFlower/UltrawideIndex#90]
Hello. thank you for making this fix first btw. so as the title says nukem framegen mod does not work with this fix. is there maybe a solution? the only one was to remove this fix and the mod would work. I hope there's a way to use both together

**Comment by RoseTheFlower** [comment]
Where can I download that mod?

**Comment by DiamondQarp** [comment]
nexus mods

**Comment by RoseTheFlower** [comment]
> nexus mods

That's vague. Do you have the link?

**Comment by DiamondQarp** [comment]
https://www.nexusmods.com/site/mods/738?tab=files

**Comment by RoseTheFlower** [comment]
Which file or version should I download?

**Comment by DiamondQarp** [comment]
i explained above. or do you need more instructions?

**Comment by RoseTheFlower** [comment]
Try `dlssg-to-fsr3-0.100 (Universal)` and then use the files from plugin_asi_loader. In my testing, everything gets loaded that way, though I can't speak to whether there would be any conflicts with the FPS mod and the FG, given that both are expected to affect the FPS. It's not something I can test on my old card that doesn't offer the DLSS option.

**Comment by RoseTheFlower** [comment]
Why not use the native FSR added in update 1.04?

**Comment by DiamondQarp** [comment]
cant use FG with dlss. its much better than fsr with FG. more fps and better image quality

**Comment by RoseTheFlower** [comment]
There's nothing else I can suggest, so I'll close, as the issue isn't caused by the mod.
