### ISSUE TITLE
[Silent Hill 2 Remake] Doesn't work anymore with the latest patch

### ISSUE THREAD

**Issue by CaptainKashup** [RoseTheFlower/UltrawideIndex#93]
Doesn't work anymore since today's 1.06 patch

**Comment by CaptainKashup** [comment]
Alright so I checked and theorically, the game still runs at 60FPS during the cutscenes, but the animations are back to 30FPS.

**Comment by RoseTheFlower** [comment]
OK, thanks for the report! Found the culprit and adapted to the new code in v.1.1.1. Give it a try and please close the issue if it works.

**Comment by CaptainKashup** [comment]
Yup, that fixed it, thanks !

**Comment by Berlinchild89** [comment]
So it seems it´s not working for Patch 1.07, since I added the files cutscene is still 16:9 and it just crashes?
