### ISSUE TITLE
RDR2 Ultrawide fix error

### ISSUE THREAD

**Issue by FonDUEM** [RoseTheFlower/UltrawideIndex#94]
Hello, I'm receiving the following error message, "Failure to find the target app process or the fix file." I'm not sure what I'm doing wrong as I followed the instructions listed on the download page. Any help or insight is appreciated. 

![Screenshot 2024-12-05 071309](https://github.com/user-attachments/assets/27d84c11-0b0f-4005-9069-db748fecca78)

**Comment by RoseTheFlower** [comment]
Hi, my RDR2 fix is in the form of a trainer but the console output you are showing is not consistent with its behavior. It also doesn't look like the type of error message it would produce. Can you tell me more about how you run it?

**Comment by FonDUEM** [comment]
Thank you for getting back to me. I followed the instructions listed on the download page. Unpacked the zip, started the game, and ran the fix applicator after the game reached the main menu. I have RDR2 on Steam, so I also attempted to launch the game with, "Run RDR and Fix - Steam" however Steam gives the error, "An error occurred when launching this game: No licenses" and then I receive the previously mentioned error after the 50 seconds are up. I've attempted a few troubleshooting steps as well, such as ensuring the game and fix are in the same drive and placing the fix in the game folder.

**Comment by RoseTheFlower** [comment]
The fix on this repo is for Red Dead Redemption released on PC this year, not for RDR2 released in 2019.

**Comment by FonDUEM** [comment]
Ah my mistake, thank you for clarifying.

**Comment by RoseTheFlower** [comment]
No worries. You're not the first person to get confused. I'll update the description to make it even clearer.

**Comment by brickphone** [comment]
@RoseTheFlower I'm having the same issue, can you clarify what you mean by this "this repo is for Red Dead Redemption released on PC this year, not for RDR2 released in 2019." ?

**Comment by RoseTheFlower** [comment]
Both Red Dead Redemption games are on PC now. Attempting to use my mod for Red Dead Redemption 1 on Red Dead Redemption 2 won't work.
