### ISSUE TITLE
Path of Exile 2 support

### ISSUE THREAD

**Issue by corosou** [RoseTheFlower/UltrawideIndex#96]
Hi,

First of all, thank you for the great work!

PoE2 is releasing today and I noticed the game does not support UltraWide, however using the PoE1 PoEUltrawideRose.asi does force PoE2 into UltraWide as well.

Although it does work, I am seeing what appears to be a white unrendered box on the left side of the login screen:

![image](https://github.com/user-attachments/assets/d019ed76-4197-4013-a6a9-4190d0cb1b7e)

Any chance you can please take a look at PoE2 and release an update?

You can download the client from https://pathofexile2.com/download

Best Regards!

**Comment by Vraknel** [comment]
Was very similar in PoE1 and it worked flawlessly.  Most likely GGG didn't fully animate the static menu scene as it's not intended to go this wide.  Guess we'll see shortly.

**Comment by RoseTheFlower** [comment]
Yeah, looks like a static background that simply doesn't have enough width to span the whole screen. The white/orange bars appear to be the background color behind that.

**Comment by TheDarkFleet** [comment]
I know this is not an issue with the poe1 release, however just commenting here as the existing poe1 mod works for 'most' things in poe2 aside from the world map which becomes almost unusable in some instances due to 'flickering' due to the map not staying centered.

**Comment by RoseTheFlower** [comment]
> I know this is not an issue with the poe1 release, however just commenting here as the existing poe1 mod works for 'most' things in poe2 aside from the world map which becomes almost unusable in some instances due to 'flickering' due to the map not staying centered.

Addressed that with the [dedicated release for Path of Exile 2](https://github.com/RoseTheFlower/UltrawideIndex/releases/tag/pathofexile2).

**Comment by livejamie** [comment]
> > I know this is not an issue with the poe1 release, however just commenting here as the existing poe1 mod works for 'most' things in poe2 aside from the world map which becomes almost unusable in some instances due to 'flickering' due to the map not staying centered.
> 
> Addressed that with the [dedicated release for Path of Exile 2](https://github.com/RoseTheFlower/UltrawideIndex/releases/tag/pathofexile2).

Do you have a one-time non-crypto way to donate to you? Buymeacoffee or Paypal, for example? Alternatively, do you have a favorite charity?

**Comment by RoseTheFlower** [comment]
> Do you have a one-time non-crypto way to donate to you? Buymeacoffee or Paypal, for example? Alternatively, do you have a favorite charity?

Patreon allows to join for any amount and cancel right away, as some people do. Thanks!
