### ISSUE TITLE
Support/Guidance for Far Cry 4 on Linux

### ISSUE THREAD

**Issue by Cwavs** [RoseTheFlower/UltrawideIndex#98]
I was wondering if I could get some guidance on running the Far Cry 4 mod on Linux, or maybe a Linux version? It seems to be an executable you're supposed to run whilst the game is open and running, however I'm not certain on the best way to run this under proton. 

I'm guessing it needs to be run in the same environment as the game, however I'm not aware of a way to do this easily after the game has launched.

**Comment by RoseTheFlower** [comment]
Hi, see my [general instructions](https://github.com/RoseTheFlower/UltrawideIndex/blob/main/instructions/linux.md) for Linux. There's a linked thread that has messages from people running a trainer on Linux, which is essentially the same thing in that it's injected into a running process.

**Comment by Cwavs** [comment]
Thanks for the fast response. So I have to run it through bottles rather than through steam?

**Comment by RoseTheFlower** [comment]
Bottles has been reported to be one of the viable options, yes, but I don't think it's the only one.

**Comment by Cwavs** [comment]
Right, thank you!
